server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        # Route 1: Auth Service (Register, Login, Token, Users)
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**

        # Route 2: Order Service (Order management & Webhook simulator)
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/orders/**

        # Route 3: Payment Webhook Service (HMAC & Idempotency)
        - id: payment-webhook-service
          uri: ${PAYMENT_WEBHOOK_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/webhooks/**

        # Route 4: Product Service (Catalog & Stock)
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/products/**

application:
  security:
    jwt:
      rsa:
        public-key-location: ${RSA_PUBLIC_KEY_LOCATION:classpath:certs/public_key.pem}
